services:
  cmy-vx:
    container_name: condo-manager
    image: condo-manager:latest
    restart: always
    ports:
      - "13845:13845"
    env_file:
      - local.env
    environment:
      - DOCKER_TIMEZONE=America/Caracas
#  cmy-vx-2nd:
#    container_name: condo-manager-2nd
#    image: condo-manager:latest
#    restart: always
#    ports:
#      - "13855:13855"
#    environment:
#      - "PORT=13855"
