  services:
  - type: web
    name: condo-manager
    runtime: docker
    repo: https://github.com/yazalulloa/condo-manager
    plan: free
    envVars:
      - key: local.env
        sync: false
    region: ohio
    dockerContext: .
    dockerfilePath: ./Dockerfile.jvm

  - type: web
    name: condo-manager
    runtime: image
    image:
      url: quay.io/keycloak/keycloak:25.0.1


version: "1"
